### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by dan-zeman** [UniversalDependencies/UD_Afrikaans-AfriBooms#1]
Some accented letters in the treebank are wrongly encoded. It looks as if a multi-byte UTF-8 character was mis-interpreted as an 8-bit encoding, then the individual bytes encoded again as UTF-8 characters. For example, the sentence test-s201:

_In hierdie opsig moet ons die oorlede president van die African National Congress, Oliver Reginald Tambo, salueer vir dit wat hy deur vastelands- en **wÃªreldliggame geÃ¯nisieer** en bekendgestel het en wat later 'n kompas vir die vreedsame oplossing van die konflik in ons land sou word._

**Comment by peedirix** [comment]
These should also be fixed in the latest commit.
